### PR TITLE
Sine wave cloud

### PR DESCRIPTION
**Pull request by gomako**
After the fascinating chaos of the live stream I thought it'd be wrong not to add a harmonic cloud. It's a bit basic but I wasn't sure how far we could go in terms of colour and stuff?

### CODE REVIEW

**Comment by shiffman** [comment]
I know I answered this already in slack, but in case anyone is following along here, colors and all sorts of anything are possible here, but to consider for the actual printed tags it will have to be thin black outlines only!

**Comment by gomako** [comment]
I think I'll close this and do something a bit more interesting, wasn't sure how the badges were going to work. I dipped in and out of the live stream!

**Comment by meiamsome** [comment]
@gomako Yes, sorry about this being not that clear - perhaps I should add something to the README

**Comment by gomako** [comment]
@meiamsome No worries, the site version is going to be just for fun and the outline version is going to be used to cut out the badge or something?

**Comment by meiamsome** [comment]
@gomako Yes, I think the easiest way to ensure your code is compatible is to check that the `stroke` parts of your code create the complete shape you want, and if you can, ensure that the outline hasn't got any gaps in it. Then if you chose to add a fill or change the stroke style it'll only be available on the site not in real life.

**Pull request closed without merging**
