### PR TITLE
Added britishCloud Function - 3 clouds in 1!

### PR DESCRIPTION
**Pull request by Jools69**
Added a british cloud that randomly shows lightning, rain or snow!

### CODE REVIEW

**Comment by meiamsome** [comment]
Nice! I merged it but I think you're too late to be printed and used irl :( Not totally sure, though

**Comment by Jools69** [comment]
Ah, no worries - I couldn't find a closing date, but had fun doing it anyway. I think I also read that it probably wouldn't be suitable for printing as it doesn't have a dark outline.
It was also my first go at using Github so definitely useful!
Regards,Jools.

**Comment by meiamsome** [comment]
@Jools69 
It looks like it might actually make it in - and we have something that can add black borders automatically now. It still looks a bit weird but hopefully it makes it in!

**Comment by shiffman** [comment]
you might still make it, we're slow and behind!

**Pull request merged**
