### PR TITLE
Update generators.js

### PR DESCRIPTION
**Pull request by yy2h8**

### CODE REVIEW

**Comment by meiamsome** [comment]
Thanks!

I like this design concept - and it's good to see some randomness used to help create more unique clouds. The centre isn't coloured white on the website, but this is not actually that problematic for the end goal. So, it would be nice to have that filled in but not a requirement. Thanks again

**Comment by yy2h8** [comment]
Thank you for merging my code!

Its awesome to be a part of this project. Now that its on the site, i
realized the inside color problem. Starting to work on it right now:)

**Comment by meiamsome** [comment]
You should be able to open index.html on your browser locally and see the results, if you haven't been doing that already!

**Comment by yy2h8** [comment]
Thanks for the tip! Will sure do that

**Pull request merged**
