### PR TITLE
Cleaned up some messy code, added ability to 'arrow' through clouds.

### PR DESCRIPTION
**Pull request by TurqDevDesign**
Cleaned up some messy code, added ability to scroll through clouds with arrow keys (originally suggested by @G4m3M4ni4c).

### CODE REVIEW

**Comment by meiamsome** [comment]
Looks like random is included in the list when using arrow keys?

**Comment by TurqDevDesign** [comment]
It is, it didn't make sense to specifically exclude 'random' from the list, since that's a construct of the sketch, not the selector. My only thought is that I could pass in an extra property to the list of selectable options that would determine if the option would be iterable with anything other than a click. For instance, I could initialize the array as: 
```
let selectOptions = {
            "random": {
                value          : "Random",
                group          : "default",
                softItteration : false 
            }
        };
```

Then simply set softItteration to true on all other items. 
I just wasn't entirely certain that this functionality was necessary at this point in time. What do you think?

**Comment by meiamsome** [comment]
I mean, I was aware of the issue and was still confused by the behaviour (Scrolling between them appears to be random clouds when it should be stylistically similar). It would be a nice to have to exclude it somehow... Is it not the case that it's the only one with group "default"? restricting to group "community" would suffice I think?

**Comment by TurqDevDesign** [comment]
That would work, but again, the "default" group is the only one that is a construct of the selector. The "community" group is a construct of the sketch. For something like this, all of the functionality of the selector class should stay within the selector class, and then the sketch just has access to the properties and methods that the selector defines upon itself. If I start frankensteining the class with the application, implementing keywords or functionality within the class that is specific to the application, then I'm removing the reusability of the class in future projects. Can that be done? Absolutely, but it defeats the purpose of using a class to organize our data in the first place. 

Passing an extra property to each item in `selectOptions` works because it keeps the information separate from the functionality. And it makes it optional, so it fits more than just our one use-case. Does that make sense?

**Comment by meiamsome** [comment]
But you don't need to know that it's the "community" group, just that you can have a `nextItemInGroup` method or something - the groups have semantic meaning both in the UI and in the program state, so why not use them...

**Comment by TurqDevDesign** [comment]
Ah, I see what you're saying now, but using that approach would still show `Random` it would just show it at the beginning, instead of being in alphabetical order. Is that what you want?

**Comment by meiamsome** [comment]
But wouldn't it just not be included because the `previousItemInGroup` wouldn't auto move to it?

I'm not sure if this is even a sensible way to browse clouds any more... my head hurts

**Comment by TurqDevDesign** [comment]
I finally fixed the issue, `random` is still in the list and can be toggled with the arrow keys, but it's sorted to the beginning. I achieved this by sorting the group names, and then sorting the items within the groups, but kept a consistent indexing from beginning to end, regardless of group. I also went in and refactored (Yes, I refactored again! I know, it's getting tiresome) and reorganized some code. This should make it a bit easier to read and maintain. Let me know what you think.

**Comment by meiamsome** [comment]
That's a lot more user friendly!

**Pull request merged**
