### PR TITLE
Update generators.js

### PR DESCRIPTION
**Pull request by juansrx**
function squareBlueCloud()

### CODE REVIEW

**Comment by JonathanHHenson** [comment]
Could you use `push()` and `pop() ` when changing the drawing settings so that your changes don't cause collateral effect to the project. Could you also fix your bounding box so that the name shows properly (once you have inserted the push and pop, the bounding box would be `[width / 2 - maxLen * 15 / 2, height / 2 - maxLen * 15 / 2, maxLen * 15, maxLen * 15]`)

**Comment by meiamsome** [comment]
@G4m3M4ni4c It should be fine without push/pop, because these are reset when drawing occurs again

**Comment by JonathanHHenson** [comment]
@meiamsome Ok, that's cool. @juansrx If you don't add push/pop, you can use the bounding box `[width / 2, height / 2, maxLen * 15, maxLen * 15]`

**Comment by JonathanHHenson** [comment]
@juansrx I have made some changes to fix your cloud, please validate that you are good with the changes, and I will merge the PR.

**Comment by juansrx** [comment]
@G4m3M4ni4c Hello, thanks for your help, feel free to make any change you need, I'm completely ok with them.

**Comment by meiamsome** [comment]
I really like your cloud, by the way!

**Comment by juansrx** [comment]
Thank you

**Comment by meiamsome** [comment]
@juansrx I don't think this cloud will be usable in its current form for the name tags because it doesn't really have room for a name (And I don't think colour is necessarily allowed). Do you want to whip up a b&w one which is primarily the border?

**Comment by juansrx** [comment]
@meiamsome I made a pull request with some changes, feel free to tell me if you need something else.

**Pull request merged**
